参数说明
objs：这是你想要合并的对象列表，可以是 Series、DataFrame 的实例列表。

axis：定义了合并的方向。默认值为 0，意味着沿着行（垂直）方向合并。如果设为 1，则沿着列（水平）方向合并。

join：决定了如何处理重叠的轴标签，默认为 'outer'，表示保留所有标签，对于没有对应值的位置填充 NaN。如果设置为 'inner'，则仅保留交集部分的标签。

ignore_index：布尔值，默认为 False。如果设置为 True，则在输出的 DataFrame 中忽略原索引，重新生成一个从 0 开始的整数索引。

keys：当沿着某一轴合并时，可以为每个对象添加一个分层的索引，以区分来源。

levels：与 keys 配合使用，用于指定分层索引的级别。

names：为结果中的轴（行或列）指定名称。

verify_integrity：布尔值，默认为 False。如果设为 True，则检查新轴是否有重复的标签，如果有，则抛出错误。

copy：布尔值，默认为 True。控制是否复制数据，默认总是复制数据以避免修改源数据。

In [14]:
import pandas as pd
from string import ascii_letters
d1, d2 = {}, {}
for i in range(26, 31):
    w = ascii_letters[i]
    d1[w] = [w + str(j) for j in range(1, 5)]
    d2[w] = [w + str(j) for j in range(1, 6)]

del d2['E']
d2['F'] = ['F' + str(j) for j in range(1, 6)]
df1, df2 = pd.DataFrame(d1), pd.DataFrame(d2)

In [15]:
pd.concat([df1, df2])

    A   B   C   D    E    F
0  A1  B1  C1  D1   E1  NaN
1  A2  B2  C2  D2   E2  NaN
2  A3  B3  C3  D3   E3  NaN
3  A4  B4  C4  D4   E4  NaN
0  A1  B1  C1  D1  NaN   F1
1  A2  B2  C2  D2  NaN   F2
2  A3  B3  C3  D3  NaN   F3
3  A4  B4  C4  D4  NaN   F4
4  A5  B5  C5  D5  NaN   F5

In [16]:
pd.concat([df1, df2], join = "inner")

    A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4
4  A5  B5  C5  D5

In [17]:
pd.concat([df1, df2], axis = 1)

     A    B    C    D    E   A   B   C   D   F
0   A1   B1   C1   D1   E1  A1  B1  C1  D1  F1
1   A2   B2   C2   D2   E2  A2  B2  C2  D2  F2
2   A3   B3   C3   D3   E3  A3  B3  C3  D3  F3
3   A4   B4   C4   D4   E4  A4  B4  C4  D4  F4
4  NaN  NaN  NaN  NaN  NaN  A5  B5  C5  D5  F5

In [18]:
pd.concat([df1, df2], axis = 1, join = "inner")

    A   B   C   D   E   A   B   C   D   F
0  A1  B1  C1  D1  E1  A1  B1  C1  D1  F1
1  A2  B2  C2  D2  E2  A2  B2  C2  D2  F2
2  A3  B3  C3  D3  E3  A3  B3  C3  D3  F3
3  A4  B4  C4  D4  E4  A4  B4  C4  D4  F4